# 开发环境配置
# 数据源配置，请修改为你项目的实际配置
server:
  port: 8092

spring:
  datasource:
    username: root
    password: "root"
    url: jdbc:mysql://localhost:3306/sip?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 连接池的配置信息
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 50
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 600
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL


  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: redis2018
    host: 49.232.209.76
    port: 6379
#    password: redis@GBDP
    password: "@GBDP2020@redis"


resources:
  paths: pic,pics,gbdpcloud-file,contentFile

swagger:
  enable: true
